// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEbQ_qwM53xbYxrF39kee2JRFDSy943uo',
    appId: '1:90348594257:web:6ae31c2a338c7e1aba0470',
    messagingSenderId: '90348594257',
    projectId: 'esame-finale-marchisio',
    authDomain: 'esame-finale-marchisio.firebaseapp.com',
    storageBucket: 'esame-finale-marchisio.firebasestorage.app',
    measurementId: 'G-7XPG7WBVDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoThYpO3sueGMdKB_i3F5PLqmDUqn1U_0',
    appId: '1:90348594257:android:af15da52f9b76029ba0470',
    messagingSenderId: '90348594257',
    projectId: 'esame-finale-marchisio',
    storageBucket: 'esame-finale-marchisio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5OZ_n33zeJYT2rQ0cYV20n6DLf5zMoiE',
    appId: '1:90348594257:ios:98bf19d76ccea6d1ba0470',
    messagingSenderId: '90348594257',
    projectId: 'esame-finale-marchisio',
    storageBucket: 'esame-finale-marchisio.firebasestorage.app',
    iosBundleId: 'com.example.esameFinaleMarchisio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5OZ_n33zeJYT2rQ0cYV20n6DLf5zMoiE',
    appId: '1:90348594257:ios:98bf19d76ccea6d1ba0470',
    messagingSenderId: '90348594257',
    projectId: 'esame-finale-marchisio',
    storageBucket: 'esame-finale-marchisio.firebasestorage.app',
    iosBundleId: 'com.example.esameFinaleMarchisio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEbQ_qwM53xbYxrF39kee2JRFDSy943uo',
    appId: '1:90348594257:web:358230da5700f3bcba0470',
    messagingSenderId: '90348594257',
    projectId: 'esame-finale-marchisio',
    authDomain: 'esame-finale-marchisio.firebaseapp.com',
    storageBucket: 'esame-finale-marchisio.firebasestorage.app',
    measurementId: 'G-SCGF3Z6T83',
  );
}
